// starters/vue-vite/src/App.vue
<template>
  <MotionConfig reduced-motion="user">
    <main style="min-height: 1800px; padding: 32px">
      <button
        data-testid="motionwind-e2e"
        class="animate-hover:scale-105 animate-tap:scale-95 animate-focus:scale-102 animate-duration-80"
      >
        Motionwind + Vue
      </button>

      <div
        data-testid="motionwind-variant"
        class="animate-variant-hidden:opacity-0 animate-variant-visible:opacity-100 animate-from-hidden animate-to-visible animate-duration-80"
      >
        Variant
      </div>

      <button
        data-testid="motionwind-layout-toggle"
        @click="shifted = !shifted"
      >
        Toggle layout
      </button>
      <div
        data-testid="motionwind-layout"
        class="animate-layout-position animate-duration-400"
        :style="{
          marginLeft: shifted ? '120px' : '0',
          width: '24px',
          height: '24px',
          background: 'black',
        }"
      />

      <div
        data-testid="motionwind-drag"
        class="animate-drag-x animate-drag-momentum-false animate-drag:scale-105"
        style="width: 40px; height: 40px; background: royalblue"
      />

      <svg
        width="40"
        height="40"
        viewBox="0 0 40 40"
        aria-label="Motionwind SVG fixture"
      >
        <path
          data-testid="motionwind-svg"
          d="M4 20 L36 20"
          fill="none"
          stroke="currentColor"
          stroke-width="4"
          class="animate-initial:path-length-0 animate-enter:path-length-1 animate-duration-80"
        />
      </svg>

      <div style="height: 1100px" />
      <div
        data-testid="motionwind-inview"
        class="animate-initial:opacity-0 animate-inview:opacity-100 animate-once animate-amount-50 animate-duration-80"
      >
        In view
      </div>
    </main>
  </MotionConfig>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { MotionConfig } from "motion-v";

const shifted = ref(false);
</script>

// starters/expo/App.tsx
import { Text } from "react-native";
import { defineConfig, MotionwindProvider, mw } from "motionwind-react-native";

const config = defineConfig({
  adapter: "react-native",
  reducedMotion: "user",
  strict: true,
});

export default function App() {
  return (
    <MotionwindProvider config={config}>
      <mw.Pressable
        testID="motionwind-e2e"
        accessibilityRole="button"
        className="animate-hover:scale-105 animate-tap:scale-95 animate-focus:scale-102 animate-duration-80"
      >
        <Text>Motionwind + Expo</Text>
      </mw.Pressable>
      <mw.View
        testID="motionwind-variant"
        className="animate-variant-hidden:opacity-0 animate-variant-visible:opacity-100 animate-from-hidden animate-to-visible animate-duration-80"
      >
        <Text>Variant</Text>
      </mw.View>
    </MotionwindProvider>
  );
}
